<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Lihat detail</name>
   <tag></tag>
   <elementGuidId>d46c384b-2915-474c-8ff4-d93e6526fa3b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.sl-link.sl-link-icon.fw-semibold.text-nowrap</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[3]/div/div[3]/div/div/div/div/a/div/div/div[4]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>26d72be4-e9ae-48b8-ab5e-160e9458e700</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sl-link sl-link-icon fw-semibold text-nowrap</value>
      <webElementGuid>06f57e87-1a1b-4eb1-be71-2cd02915f334</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lihat detail</value>
      <webElementGuid>6a7cb31e-0d52-4050-a0ef-13a85e23dd6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;d-flex flex-column align-item justify-content-between h-100&quot;]/div[@class=&quot;mb-4&quot;]/div[@class=&quot;bg-secondary-50&quot;]/div[@class=&quot;container py-5&quot;]/div[@class=&quot;sl-tabs my-2&quot;]/div[@class=&quot;tab-content&quot;]/div[@class=&quot;tab-pane active px-0 px-md-5&quot;]/a[@class=&quot;text-decoration-none&quot;]/div[@class=&quot;card rounded-0 border-1&quot;]/div[@class=&quot;card-body p-4 d-flex flex-column gap-4&quot;]/div[@class=&quot;d-flex justify-content-end&quot;]/span[@class=&quot;sl-link sl-link-icon fw-semibold text-nowrap&quot;]</value>
      <webElementGuid>4ea16d6a-2e0f-40cd-a6e6-97e8b1179ff6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[3]/div/div[3]/div/div/div/div/a/div/div/div[4]/span</value>
      <webElementGuid>603a088e-d918-4da1-97e2-f7b853654b49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/span</value>
      <webElementGuid>a0c76f2e-2ef4-4c7c-8c99-bc0acd791968</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Lihat detail' or . = 'Lihat detail')]</value>
      <webElementGuid>dd3bc400-ccc0-421d-8964-8dd5fed8a97a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
