<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_credentials.passcode</name>
   <tag></tag>
   <elementGuidId>19e8a644-aa74-4c4d-8aa2-0f5702d3b30c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input36</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input36']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>736e8653-4de7-43b8-8c46-2ad6a7aff9f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>363261f8-2d2f-47e7-a7a0-0da7f2159632</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>credentials.passcode</value>
      <webElementGuid>7a51b335-9448-4238-9f53-653986c56144</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input36</value>
      <webElementGuid>7ebdbbc2-dae9-43f4-aa7f-d5263aa046dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>current-password</value>
      <webElementGuid>595ad234-124e-4763-b767-c76f71395c19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>password-with-toggle</value>
      <webElementGuid>23551c82-8371-4b49-8a27-fb494e58f392</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input36&quot;)</value>
      <webElementGuid>c64fd71d-bd45-43dd-b916-eb329357e643</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input36']</value>
      <webElementGuid>c25d6048-facc-4eef-b1de-3af76a89389a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form20']/div/div[3]/div[2]/div[2]/span/input</value>
      <webElementGuid>6bd11311-f894-4a5b-8d3b-4f7db411c47b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/span/input</value>
      <webElementGuid>99f74901-5af7-4b4f-ba74-772e33c10650</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @name = 'credentials.passcode' and @id = 'input36']</value>
      <webElementGuid>47451f6a-77e6-47af-a146-a5647a9678cc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
