<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Keep me signed in</name>
   <tag></tag>
   <elementGuidId>c5a308b5-3dff-4e2a-954c-a6f7e5845a26</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>label.hover</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='form20']/div/div[3]/div[3]/div/span/div/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>5c289757-0c49-46cb-8338-82bb49e717dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>input44</value>
      <webElementGuid>864f79ad-cfcb-47d0-a5b2-467c4966024f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-se-for-name</name>
      <type>Main</type>
      <value>rememberMe</value>
      <webElementGuid>14f8bf5a-7af7-4c8b-9550-f2d259c27acf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hover</value>
      <webElementGuid>de107e8b-f9b6-4110-9376-1c7d233ae1f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Keep me signed in</value>
      <webElementGuid>35cfc613-de7b-4561-bc7b-2f9e6f60b09d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form20&quot;)/div[@class=&quot;o-form-content o-form-theme clearfix&quot;]/div[@class=&quot;o-form-fieldset-container&quot;]/div[@class=&quot;o-form-fieldset o-form-label-top&quot;]/div[@class=&quot;o-form-input&quot;]/span[@class=&quot;o-form-input-name-rememberMe&quot;]/div[@class=&quot;custom-checkbox&quot;]/label[@class=&quot;hover&quot;]</value>
      <webElementGuid>265dc667-71a4-4af1-96f5-415476fcde09</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form20']/div/div[3]/div[3]/div/span/div/label</value>
      <webElementGuid>b8a0104c-800e-491a-b523-0ff33076a8b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div/label</value>
      <webElementGuid>c960404e-03b3-4d09-8329-366f70839f12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Keep me signed in' or . = 'Keep me signed in')]</value>
      <webElementGuid>1a393d2b-4452-4a52-bdcd-432c95c128df</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
